#分库数据库设置
sharding.jdbc.datasource.names: ds_0,ds_1
#数据分片设置
sharding.jdbc.datasource.ds_0:
  type: org.apache.commons.dbcp.BasicDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/demo_ds_0?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true
  username: root
  password: 123456

sharding.jdbc.datasource.ds_1:
  type: org.apache.commons.dbcp.BasicDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/demo_ds_1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true
  username: root
  password: 123456

#分库规则配置 分库键不要使用自增的主键
sharding.jdbc.config.sharding.default-database-strategy.inline:
  sharding-column: user_id
  algorithm-expression: ds_$->{user_id % 2}

#t_order表分片规则配置 分片键不要使用自增的主键
sharding.jdbc.config.sharding.tables.t_order:
  actual-data-nodes: ds_$->{0..1}.t_order_$->{0..1}
  table-strategy.inline:
    sharding-column: order_id
    algorithm-expression: t_order_$->{order_id % 2}
    key-generator-column-name: order_id
#t_order_item表分片规则配置
sharding.jdbc.config.sharding.tables.t_order_item:
  actual-data-nodes: ds_$->{0..1}.t_order_item_$->{0..1}
  table-strategy.inline:
    sharding-column: order_id
    algorithm-expression: t_order_item_$->{order_id % 2}
    key-generator-column-name: order_item_id
